config/routes.rb
CodeForAmerica::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get '/sign-in'  => 'sessions#new',     as: :sign_in
    get '/sign-out' => 'sessions#destroy', as: :sign_out
  end

  resources :users, only: [:show, :index, :edit, :update]

  resources :applications, only: [:index, :show] do
    resources :deployed_applications, only: [:new, :create], controller: 'applications/deployed_applications'
  end

  resources :brigades do
    collection do
      post :find
    end

    member do
      get :join
      get :leave
    end

    resources :deployed_applications, only: [:new, :create, :index], controller: 'brigades/deployed_applications'
  end

  resources :locations do
    collection do
      post :find
    end

    resources :deployed_applications, only: [:new, :create, :index], controller: 'locations/deployed_applications'
  end

  resources :deployed_applications, only: [:index, :new, :create, :show]
  resources :challenges, only: [:new, :create, :index]
  resources :home
  root :to => 'home#index'

  match "/pages/*id" => 'pages#show', :as => :page, :format => false

  match '/about' => 'high_voltage/pages#show', :id => 'about'

end

app/models/brigade.rb
class Brigade < ActiveRecord::Base
  has_many :deployed_applications
  has_many :applications, through: :deployed_applications

  has_and_belongs_to_many :users

  validates :name, presence: true
  validates :point_of_contact_address, presence: true

  def to_s
    name
  end
end

app/controllers/brigades/deployed_applications_controller.rb
class Brigades::DeployedApplicationsController < ApplicationController
  load_resource :brigade

  def new
    @deployed_application = @brigade.deployed_applications.build
    @deployed_application.build_location
    @deployed_application.build_brigade
  end

  def create
    @deployed_application = @brigade.deployed_applications.build params[:deployed_application]

    if @deployed_application.save
      redirect_to @deployed_application, notice: 'The application was deployed successfully!'
    else
      flash[:error] = 'The application could not be deployed'
      render :new
    end
  end

  def index
    @deployed_applications = @brigade.deployed_applications.search(params[:query])
  end
end

app/controllers/brigades_controller.rb
class BrigadesController < ApplicationController
  before_filter :authenticate_user!, only: [:join, :leave]

  def find
    @brigade = Brigade.find_by_name params[:brigade]

    if @brigade
      redirect_to brigade_deployed_applications_path(@brigade)
    else
      redirect_to deployed_applications_path(filter_by: 'brigades'), notice: "There are no apps currently deployed by #{params[:brigade]}"
    end
  end

  def create
    @brigade = Brigade.new params[:brigade]

    if @brigade.save
      render json: @brigade, status: 200
    else
      render json: @brigade.errors, status: 400
    end
  end

  def index
    @brigades = Brigade.all(:order => 'name')
  end

  def show
    @brigade = BrigadeDecorator.new(Brigade.find(params[:id]))
  end

  def join
    @brigade = Brigade.find params[:id]
    current_user.join_brigade(@brigade)
    params[:redirect_uri] ||= brigade_path(@brigade)
    redirect_to params[:redirect_uri]
  end

  def leave
    @brigade = Brigade.find params[:id]
    current_user.leave_brigade(@brigade)
    redirect_to brigade_url(@brigade)
  end
end

app/views/brigades/_deployed_applications_search_form.html.erb
<div class="internal-search-box">
  <%= form_tag find_brigades_path do %>
    <%= label_tag :brigade, 'Brigade' %>
    <%= text_field_tag :brigade %>
    <%= submit_tag 'Search' %>
  <%end%>
</div>

app/views/brigades/index.html.erb
<header class="page-id">
  <h1>
    Brigades
  </h1>

</header>

<% if @brigades.empty? %>
  <h3> There aren't any brigades that match that criteria! </h3>
<% else %>
  <p>
  Brigades are groups of passionate local citizens committed to making a difference: they are standing up apps, gathering civic data, and hosting events, ranging from hackathons to unconferences. See if one of the brigades below is in your community; if not, start one by challenging your city to <a href="/applications">deploy an app.</a>
  </p>
  <table class="all-cities" cellpadding="4" id="sortable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @brigades.each do |brigade| %>
        <tr id="<%="brigade_#{brigade.id}"%>" class="<%= cycle "odd", "even" %>">
          <td><%= brigade.name %></td>
          <td><%= link_to 'Show', brigade%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<%end%>

app/views/brigades/show.html.erb
<header class="page-id">
  <h1><%= @brigade.name %></h1>
</header>

<div class="container-fluid">
  <div class="row-fluid">
    <!-- main -->
    <div id="leftcolumn" class="span8">

      <table class="all-cities" cellpadding="4" id="sortable">
        <thead>
          <tr>
            <th>App Name</th>
            <th width="17%">Status</th>
            <th>Location</th>
            <th>Action</th>
          </tr>
        </thead>

        <%= render @brigade.deployed_applications, brigade_name: false %>
      </table>
    </div>

    <div id="sidebar" class="span4">
      <div class="app-info">
        <h3>Info</h3>
        <h4><span class='icon'>Y</span> Get invlolved</h4>
        <p class='center'>
          <%= link_to 'Join the brigade to get involved!', join_brigade_url(@brigade), class: 'btn primary' if !can? :leave, @brigade%>
          <%= raw("You are a member of this brigade! #{link_to 'Leave this brigade', leave_brigade_url(@brigade), class: 'btn'}") if can? :leave, @brigade %>
        </p>

        <% if @brigade.point_of_contact_address.present? %>
          <h4><span class="icon">O</span> Connect</h4>
          <p><%= auto_link @brigade.point_of_contact_address %></p>
        <% end %>

        <h4><span class='icon'>f</span> Members</h4>
        <%= @brigade.decorated_members %>
      </div>
    </div>
  </div>
</div>