config/routes.rb
CodeForAmerica::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get '/sign-in'  => 'sessions#new',     as: :sign_in
    get '/sign-out' => 'sessions#destroy', as: :sign_out
  end

  resources :users, only: [:show, :index, :edit, :update]

  resources :applications, only: [:index, :show] do
    resources :deployed_applications, only: [:new, :create], controller: 'applications/deployed_applications'
  end

  resources :brigades do
    collection do
      post :find
    end

    member do
      get :join
      get :leave
    end

    resources :deployed_applications, only: [:new, :create, :index], controller: 'brigades/deployed_applications'
  end

  resources :locations do
    collection do
      post :find
    end

    resources :deployed_applications, only: [:new, :create, :index], controller: 'locations/deployed_applications'
  end

  resources :deployed_applications, only: [:index, :new, :create, :show]
  resources :challenges, only: [:new, :create, :index]
  resources :home
  root :to => 'home#index'

  match "/pages/*id" => 'pages#show', :as => :page, :format => false

  match '/about' => 'high_voltage/pages#show', :id => 'about'

end

app/models/application.rb
class Application < ActiveRecord::Base

  has_many :tasks
  has_many :pictures

  has_many :deployed_applications
  has_many :participating_brigades, through: :deployed_applications, source: :brigade

  validates :nid, presence: true
  validates :logo, length: { in: 0..1 }
  validate :cannot_have_more_than_four_pictures

  def cannot_have_more_than_four_pictures
    if pictures.count > 4
      errors.add(:pictures, "cannot have more than four")
    end
  end

  def to_s
    name
  end

  def deployed_application_users
    users = Array.new

    deployed_applications.map(&:brigade).each do |brigade|
      users = users + brigade.users
    end

    users.uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Errship::Rescuers
  include Errship::ActiveRecord::Rescuers

  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied."
    redirect_to root_url
  end

  protected

  def after_sign_in_path_for(user)
    request.env['omniauth.origin'] || stored_location_for(user) || user_path(user)
  end

end

app/controllers/applications/deployed_applications_controller.rb
class Applications::DeployedApplicationsController < DeployedApplicationsController
  load_resource :application
  before_filter :authenticate_user!, only: [:new]

  def new
    @deployed_application = @application.deployed_applications.build
    @location = @deployed_application.build_location
    @brigade = @deployed_application.build_brigade

    authorize! :create, @deployed_application
  end

  def create
    @deployed_application = @application.deployed_applications.build params[:deployed_application]

    if @deployed_application.save

      # if the deployed_application is created associate the current user with the brigade that
      # deployed the application
      @deployed_application.brigade.users << current_user if @deployed_application.brigade.present?
      redirect_to @deployed_application, notice: 'The application was deployed successfully!'
    else
      flash[:alert] = 'The application could not be deployed'

      @location = Location.new
      @brigade = Brigade.new
      render :new
    end
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

  def index
    @apps = Application.all
  end

  def show
    @app = AppDecorator.new(Application.find(params[:id]))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_session_links
    if current_user
       header = (content_tag :li, (raw('Welcome, ' + link_to(current_user.full_name, user_url(current_user)))))
       header << (content_tag :li, raw(link_to('Admin', rails_admin_path))) if current_user.admin?
       header << (content_tag :li, (link_to 'Sign Out', sign_out_path))
       return header
    else
      # Use '<<' to concat the two links so that they're returned together
      (content_tag :li, (link_to 'Sign In', sign_in_path, class: 'btn btn-regular')) << (content_tag :li, (link_to 'Sign Up', new_user_registration_path, class: 'btn btn-info'))
    end
  end

  def display_join_button
      (content_tag :p, (link_to 'JOIN US!', new_user_registration_path, class: 'btn-large btn-join'))
  end


  def unsorted_grouped_options_for_select(grouped_options, selected_key = nil, prompt = nil)
    body = ''
    body << content_tag(:option, prompt, { :value => "" }, true) if prompt

    grouped_options.each do |group|
      body << content_tag(:optgroup, options_for_select(group[1], selected_key), :label => group[0])
    end

    body.html_safe
  end
end

app/views/applications/_application.html.erb
<tr class="<%= cycle "odd", "even" %>", id="<%= "application_#{application.id}" %>">
  <td class="avatar">
    <%= application.logo %>
  </td>
  <td>
    <h3><%= link_to application.name, application_path(application) %></h3>
    <p><%= application.short_description %></p>
  </td>
  <td>
    <%= render 'applications/deploys', application: AppDecorator.new(application) %>
  </td>
  <td class="show-app">
    <%= link_to 'Show App', application_path(application), class: 'show-button' %>
  </td>
</tr>

app/views/applications/_deploys.html.erb
<div class='hidden' id='repository_participation'><%= application.repository_participation %></div>
<table class='small-stats'>
  <tr>
    <td class='deploy-count'><%= application.number_of_deploys %></td>
  </tr>
  <tr class='labels'>
    <td>Deploys</td>
  </tr>
</table>

app/views/applications/_small-stats.html.erb
<div class='hidden' id='repository_participation'><%= application.repository_participation %></div>
<table class='small-stats'>
  <tr>
    <%= application.repository_sparkline %>
    <td class='deploy-count'><%= application.number_of_deploys %></td>
  </tr>
  <tr class='labels'>
    <td><%= application.repository_sparkline_label %></td>
    <td>Deploys</td>
  </tr>
</table>

app/views/applications/index.html.erb
<header class="page-id">
  <h1>
    Applications You Can Deploy. Now.
  </h1>
</header>
<p>
Across the country, civic hackers are building amazing applications at hackathons and through app contests. You can leverage their efforts to redeploy those applications in your city. We've selected a few of the most easily reused and promising apps to feature on the Brigade, and added step-by-step instructions on how to get them running. Pick an app below and then recruit your friends to make it happen.
</p>
<table class="all-apps" cellpadding="4">
  <% @apps.each do |application| %>
    <%= render partial: 'application', object: application %>
  <% end %>
</table>

app/views/applications/show.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <!-- main -->
    <div id="leftcolumn" class="span8">
      <hgroup class="app-title">
        <h2>
          Work on <%= @app.name %>
        </h2>
        <h5>
          <% if can? :create, DeployedApplication %>
            <%= link_to new_application_deployed_application_path(@app), :class => "btn adjusted" do %>
              <span class="icon">(</span> Start a Deployment
            <% end %>
          <% elsif current_user == nil %>
            <%= link_to new_application_deployed_application_path(@app), :class => "btn" do %>
              <span class="icon">(</span> Sign In or Sign Up to Start a Deployment
            <% end %>

          <% end %>
        </h5>
        <div class="clear"></div>
      </hgroup>

      <%= render 'shared/application_body' %>
      </div>

    <!-- sidebar -->
    <div id="sidebar" class="span4">
      <div class="app-info">
        <%= render 'applications/small-stats', application: @app %>

        <h3>Get Info</h3>
        <h4><span class="icon">O</span> Technical</h4>

        <ul class="unstyled">
          <li><span class='icon'>5</span>&nbsp;Github URL: <%= @app.repository_url_link %></li>
          <li><span class='icon'>w</span>&nbsp;IRC Channel: <%= @app.irc_channel %></li>
          <li><span class='icon'>U</span>&nbsp;Twitter Hashtag: <%= @app.twitter_hashtag %></li>
          <li><span class='icon'>1</span>&nbsp;Mailing List: <%= @app.mailing_list_url_link %></li>
          <li><span class='icon'>f</span>&nbsp;Creator: <%= @app.creator %></li>
          <li><span class='icon'>K</span>&nbsp;License: <%= @app.license %></li>
        </ul>

        <h4><span class="icon">g</span> People <span id="user-name"></span></h4>

        <%= @app.decorated_deployed_application_users %>

        <h4><span class="icon">,</span> <%= @app.name %> is deployed in</h4>

        <!-- minimap -->
        <div class='map', id='map' style="width: 265px; height: 230px;"></div>
        <div class='hidden' id='locations'><%= @app.deployed_applications.map(&:location).uniq.map {|l| {icon_link: location_deployed_applications_url(l)}.merge(l.attributes.select{|k,v| ['latitude', 'longitude', 'name'].include?(k)}).to_json } %></div>

      </div>
    </div>

  </div>
</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyAU73pt7g1lj1KfSffmFgWfKHcbn_xJQyE&sensor=true"></script>
<script tpye='text/javascript'>
  var map;
  var markers = [];
  var latlons = [];

  function initialize_map() {
    var myOptions = {
      center: new google.maps.LatLng(39.5, -98.35),
      zoom: 3,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById("map"), myOptions);
  }


  initialize_map();

  var locations = $.parseJSON($('#locations').text())
  $.each(locations, function(index, value){
    value = $.parseJSON(value)
    latlons[index] = new google.maps.LatLng(value.latitude, value.longitude);
    markers[index] = new google.maps.Marker({ position: latlons[index], title: value.name, url: value.icon_link });
    google.maps.event.addListener(markers[index], 'click', function() {
        window.location.href = markers[index].url;
    });
    markers[index].setMap(map)
  })

  var latlngbounds = new google.maps.LatLngBounds( );
  for ( var i = 0; i < latlons.length; i++ )
  {
      latlngbounds.extend( latlons[ i ] );
  }
  map.fitBounds( latlngbounds );
</script>