config/routes.rb
CodeForAmerica::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get '/sign-in'  => 'sessions#new',     as: :sign_in
    get '/sign-out' => 'sessions#destroy', as: :sign_out
  end

  resources :users, only: [:show, :index, :edit, :update]

  resources :applications, only: [:index, :show] do
    resources :deployed_applications, only: [:new, :create], controller: 'applications/deployed_applications'
  end

  resources :brigades do
    collection do
      post :find
    end

    member do
      get :join
      get :leave
    end

    resources :deployed_applications, only: [:new, :create, :index], controller: 'brigades/deployed_applications'
  end

  resources :locations do
    collection do
      post :find
    end

    resources :deployed_applications, only: [:new, :create, :index], controller: 'locations/deployed_applications'
  end

  resources :deployed_applications, only: [:index, :new, :create, :show]
  resources :challenges, only: [:new, :create, :index]
  resources :home
  root :to => 'home#index'

  match "/pages/*id" => 'pages#show', :as => :page, :format => false

  match '/about' => 'high_voltage/pages#show', :id => 'about'

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_taggable_on :skills

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :opt_in, :location_id, :avatar, :skill_list, :avatar_cache, :github_uid,
                  :full_name, :first_name, :last_name

  validates :full_name, presence: true

  belongs_to :location
  delegate :name, to: :location, prefix: true, allow_nil: true

  has_and_belongs_to_many :brigades
  has_many :applications, through: :brigades

  scope :contactable, where(opt_in: true)

  searchable do
    text :first_name
    text :last_name
    text :skill_list
    text :location_name

    text :brigade_names do
      brigades.map { |brigade| brigade.name }
    end

    text :application_names do
      applications.map { |application| application.name }
    end
  end

  def self.find_or_create_by_email_and_github_uid(email, name, github_uid)
    #This function is about finding a user from the github oauth hash or creating
    #one if one doesn't exist.

    #Try to find the user by github_id
    user = User.find_by_email(email) || User.find_by_github_uid(github_uid)

    user || User.create(email: email, github_uid: github_uid, full_name: name)
  end

  # def update_github_uid(github_uid)
  #   update_attribute(:github_uid, github_uid)
  # end

  def password_required?
    (github_uid.blank? || password.present?) && super
  end

  def full_name
    "#{first_name} #{last_name}" unless first_name.nil? and last_name.nil?
  end

  def full_name=(name)
    split = name.split(' ', 2)
    self.first_name = split.first
    self.last_name = split.last
  end

  def is_member_of?(brigade)
    self.brigades.include? brigade
  end

  def join_brigade(brigade)
    brigade.users << self unless self.is_member_of?(brigade)
  end

  def leave_brigade(brigade)
    user = brigade.users.find_by_id(id)
    brigade.users.delete(user) if user
  end

  alias :name :full_name

end

app/controllers/users/omniauth_callbacks_controller.rb
require 'code-for-america/github_omniauth_parser'

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github

    parser = CodeForAmerica::GithubOmniAuthParser.new request.env["omniauth.auth"]
    email = parser.email
    github_uid = parser.github_uid
    name = parser.name

    # You need to implement the method below in your model
    user = current_user || User.find_or_create_by_email_and_github_uid(email, name, github_uid)

    if user.persisted?
      user.update_github_uid(github_uid)
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Github"
      sign_in_and_redirect user, :event => :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show
    @user = UserDecorator.new(User.find(params[:id]))
  end

  def edit
    @user = UserDecorator.new(User.find(params[:id]))
    @location = Location.new
  end

  def update
    @user = User.find(params[:id])

    result = false
    result = @user.update_with_password(params[:user]) unless @user.github_uid.present?
    result = @user.update_without_password(params[:user]) if @user.github_uid.present?

    if result
      sign_in(@user, :bypass => true)
      redirect_to user_path(@user)
    else
      @user = UserDecorator.new(@user)
      @location = @user.location || Location.new
      render :edit
    end
  end

  def index
    if params[:query]
      @search = User.search do
        fulltext params[:query]
      end

      @users = @search.results
    else
      @users = User.all
    end
  end
end

app/views/users/edit.html.erb
<div id="leftcolumn" class='span7'>
  <h2>User Info</h2>

  <div id="user_info" class='row'>
  <%= simple_form_for @user, html: { class: 'form-vertical' } do |f| %>

    <div class='span2'>
      <%= @user.gravatar_medium %>
      <a id="gravatar_link" class="capitalized-link" href="http://www.gravatar.com/" target="_blank" title="your gravatar is associated with your email address">change picture</a>
      <div id="gravatar_info"></div>
    </div>

    <div class='span5'>
      <%= f.input :first_name, label: 'First name' %>
      <%= f.input :last_name, label: 'Last name' %>
      <%= f.input :skill_list, label: 'Skill Set (comma separated)' %>
      <%= render partial: 'shared/location_select', locals: { f: f } %>

      <h2>Contact Settings</h2>
      <%= f.input :opt_in, label: "I want other civic hackers to be able to contact me for assistance", wrapper: :checkbox, label_html: { class: :checkbox } %>
      <br>
      <h2>Change your password</h2>
      <%= f.input :password, label: 'Password' %>
      <%= f.input :password_confirmation, label: 'Confirm password' %>
      <i>Optional, you can leave these fields blank</i>
      <br>
      <hr>

      <%= f.input :current_password, label: 'Enter your current password to make these changes' unless @user.github_uid.present? %>
      <%= f.button :submit %>
    </div>
  <% end %>
  </div>
</div>

<%= render 'shared/location_modal' %>

app/views/users/index.html.erb
<header class="page-id">
  <h1>
    People
  </h1>

  <div class="internal-search-box">
    <%= form_tag users_path, method: :get, class: 'span4', style: 'margin-top: 7px;' do %>
      <%= text_field_tag :query, session[:query], placeholder: 'Search', class: 'span3' %>
      <%= submit_tag "Search", name: nil %>
    <% end %>
  </div>
</header>

<% if @users.empty? %>
  <h3> There aren't any hackers that match that criteria! </h3>
<% else %>

  <table class="all-cities" cellpadding="4" id="sortable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Skill Set</th>
        <th>Location</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr id="<%="user_#{user.id}"%>" class="<%= cycle "odd", "even" %>">
          <td><strong><%= user.full_name %></strong></td>
          <td><%= user.skill_list %></td>
          <td>
            <% if user.location_name.blank? %>
              None listed.
            <% else %>
            <%= link_to user.location_name, location_deployed_applications_url(user.location) if user.location.present?%>
            <% end %>
          </td>
          <td><%= link_to 'Show', user%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<%end%>

app/views/users/show.html.erb
<header class="page-id">
  <h1>
    People | <span class="amp"><%= @user.full_name %></span>
  </h1>
</header>

<div id="leftcolumn" class='span7'>
  <h2>
    User Info
    <% if can? :edit, @user %>
      <%= link_to '(Edit)', edit_user_path(@user) %>
    <% end %>
  </h2>

    <div id="user_info" class='row'>
      <div class='span2'>
        <%= @user.gravatar_medium %>
      </div>

      <table class="user-info" cellpadding="4">
        <tr>
          <td class="prv-label">Name</td>
          <td><%= @user.full_name %></td>
        </tr>
        <tr>
          <td class="prv-label">Contact</td>
          <td><%= @user.contact_preference %></td>
        </tr>
        <tr>
          <td class="prv-label">Location</td>
          <td><%= @user.location_name %></td>
        </tr>
        <tr>
          <td class="prv-label">Skills</td>
          <td><%= @user.skill_set %></td>
        </tr>
        <% if @user.brigades.any? %>
        <tr>
          <td class="prv-label">Brigades</td>
          <td><%= raw @user.brigades.uniq.map{|b| link_to b.name, brigade_url(b)}.join(', ') %></td>
        </tr>
        <% end %>
      </table>
    </div>
</div>