config/routes.rb
CodeForAmerica::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get '/sign-in'  => 'sessions#new',     as: :sign_in
    get '/sign-out' => 'sessions#destroy', as: :sign_out
  end

  resources :users, only: [:show, :index, :edit, :update]

  resources :applications, only: [:index, :show] do
    resources :deployed_applications, only: [:new, :create], controller: 'applications/deployed_applications'
  end

  resources :brigades do
    collection do
      post :find
    end

    member do
      get :join
      get :leave
    end

    resources :deployed_applications, only: [:new, :create, :index], controller: 'brigades/deployed_applications'
  end

  resources :locations do
    collection do
      post :find
    end

    resources :deployed_applications, only: [:new, :create, :index], controller: 'locations/deployed_applications'
  end

  resources :deployed_applications, only: [:index, :new, :create, :show]
  resources :challenges, only: [:new, :create, :index]
  resources :home
  root :to => 'home#index'

  match "/pages/*id" => 'pages#show', :as => :page, :format => false

  match '/about' => 'high_voltage/pages#show', :id => 'about'

end

app/models/deployed_application.rb
class DeployedApplication < ActiveRecord::Base
  belongs_to :application
  delegate :name, to: :application

  belongs_to :location
  delegate :name, to: :location, prefix: true
  accepts_nested_attributes_for :location

  belongs_to :brigade
  delegate :name, to: :brigade, prefix: true
  accepts_nested_attributes_for :brigade

  validates :location, presence: true
  validates :location_id, presence: true, uniqueness: { scope: [:brigade_id, :application_id], message: "Brigade has already deployed this app in this location" }
  validates :brigade, presence: true
  validates :application, presence: true

  def self.search(query = nil)
    if query
      joins(:brigade, :application).where("brigades.name ILIKE ? OR applications.name ILIKE ?", "%#{query}%","%#{query}%" )
    else
      all
    end
  end
end

app/controllers/applications/deployed_applications_controller.rb
class Applications::DeployedApplicationsController < DeployedApplicationsController
  load_resource :application
  before_filter :authenticate_user!, only: [:new]

  def new
    @deployed_application = @application.deployed_applications.build
    @location = @deployed_application.build_location
    @brigade = @deployed_application.build_brigade

    authorize! :create, @deployed_application
  end

  def create
    @deployed_application = @application.deployed_applications.build params[:deployed_application]

    if @deployed_application.save

      # if the deployed_application is created associate the current user with the brigade that
      # deployed the application
      @deployed_application.brigade.users << current_user if @deployed_application.brigade.present?
      redirect_to @deployed_application, notice: 'The application was deployed successfully!'
    else
      flash[:alert] = 'The application could not be deployed'

      @location = Location.new
      @brigade = Brigade.new
      render :new
    end
  end
end

app/controllers/brigades/deployed_applications_controller.rb
class Brigades::DeployedApplicationsController < ApplicationController
  load_resource :brigade

  def new
    @deployed_application = @brigade.deployed_applications.build
    @deployed_application.build_location
    @deployed_application.build_brigade
  end

  def create
    @deployed_application = @brigade.deployed_applications.build params[:deployed_application]

    if @deployed_application.save
      redirect_to @deployed_application, notice: 'The application was deployed successfully!'
    else
      flash[:error] = 'The application could not be deployed'
      render :new
    end
  end

  def index
    @deployed_applications = @brigade.deployed_applications.search(params[:query])
  end
end

app/controllers/deployed_applications_controller.rb
class DeployedApplicationsController < ApplicationController

  def show
    @deployed_application = DeployedApplication.find(params[:id])
    @app = AppDecorator.new(@deployed_application.application)
  end

  def index
    @filter_type = params[:filter_by]
    @deployed_applications = DeployedApplication.all
  end
end

app/controllers/locations/deployed_applications_controller.rb
class Locations::DeployedApplicationsController < ApplicationController
  load_resource :location

  def new
    @deployed_application = @location.deployed_applications.build
    @deployed_application.build_location
    @deployed_application.build_brigade
  end

  def create
    @deployed_application = @location.deployed_applications.build params[:deployed_application]

    if @deployed_application.save
      redirect_to @deployed_application, notice: 'The application was deployed successfully!'
    else
      flash[:error] = 'The application could not be deployed'
      render :new
    end
  end

  def index
    @deployed_applications = @location.deployed_applications.search(params[:query])
    @applications_not_deployed = @location.applications_not_deployed
  end
end

app/views/deployed_applications/_deployed_application.html.erb
<tr class="<%= cycle "odd", "even" %>", id="<%= "deployed_application_#{deployed_application.id}" %>">
  <td><%= deployed_application.name %></td>
  <td>
    <% if deployed_application.deployed %>
      Deployed
    <% else %>
      In Progress
    <% end %>
  </td>
  <td><%= link_to deployed_application.location_name, location_deployed_applications_url(deployed_application.location) if Location.find_by_id(deployed_application.location_id).is_a?(Location) %></td>
  <% if brigade_name %>
    <td><%= link_to deployed_application.brigade_name, brigade_url(deployed_application.brigade) %></td>
  <% end %>
  <td><%= link_to 'Show App', deployed_application_url(deployed_application), :class => "show-button" %></td>
</tr>

app/views/deployed_applications/_form.html.erb
<%= simple_form_for @deployed_application, url: url do |form| %>
  <%= render partial: 'shared/location_select', locals: { f: form } %>
  <div class='control-group select required'>
    <label class='select required' for='deployed_application_brigade_id'>* Brigade</label>
    <div class='controls'>
      <%= form.select 'brigade_id', unsorted_grouped_options_for_select({'Existing Brigades' => Brigade.all.map{|b| [b.name, b.id]}, 'Add your own' => ['Add Brigade']}, nil, 'Choose or create a brigade'), {}, {class: 'select required brigade-selector'} %>
    </div>
  </div>
  <%= form.button :submit, 'Issue Challenge!', class: 'btn-large btn-primary' %>
<%end%>

app/views/deployed_applications/_social_network_modal.html.erb
<div class="modal fade" id="share">
  <div class="modal-header">
    <a class="close" data-dismiss="modal"></a>
    <h3>Share this deploy</h3>
  </div>

  <div class="modal-body">
    <p><a class='btn' href="http://www.facebook.com/dialog/feed?app_id=<%= SOCIAL_NETWORKS['facebook_app_id']%>&redirect_uri=http://www.facebook.com&display=popup" id="fb-control">Share with facebook</a></p>
    <p>
      <a href="https://twitter.com/share" class="twitter-share-button" data-via="cfa" data-size="large">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </p>
  </div>

  <div class="modal-footer">
    <a href="#" class="btn btn-primary" data-dismiss="modal">Done</a>
  </div>
</div>

<script type='text/javascript'>
  $('#fb-control').click(function(event){
      event.preventDefault();
      popup = window.open($(this).attr('href'), '', 'height=200,width=500')
      if (window.focus) {popup.focus()}
  })
</script>

app/views/deployed_applications/index.html.erb
<header class="page-id">
  <h1>
    Deployed Applications
  </h1>
</header>

<div class="internal-search-box">
  <%= form_tag find_locations_path do %>
    <%= text_field_tag :location, nil, placeholder: "Search by Location" %>
    <%= submit_tag 'Search' %>
  <%end%>
</div>

<% if @deployed_applications.present? %>
  <table class="all-cities" cellpadding="4" id="sortable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Location</th>
        <th>Brigade Name</th>
        <th>Action</th>
      </tr>
    </thead>

    <%= render @deployed_applications, brigade_name: true %>
  </table>
<%else%>
  <%= content_tag :h2, "There are no apps currently deployed" %>
<% end %>

app/views/deployed_applications/new.html.erb
<div class="login-box">
  <%= content_tag :h2, "Deploy #{@application_name}" %>

  <%= render 'deployed_applications/form', deployed_application: @deployed_application %>
</div>

app/views/deployed_applications/show.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <!-- main -->
    <div id="leftcolumn" class="span8">
      <hgroup class="app-title">
        <h2 style='width: 100%'><%= @deployed_application.name %> &rarr; forked from <%= link_to @deployed_application.application.name, application_url(@deployed_application.application) %></h2>
        <div class='clear'></div>
        <h4>
          <%= link_to @deployed_application.brigade.name, brigade_url(@deployed_application.brigade) %>
          in <%= link_to @deployed_application.location.name, location_deployed_applications_url(@deployed_application.location) %>
          <% if @deployed_application.deployed %>
            has deployed this app
          <% else %>
            is deploying this app
          <% end %>
        </h4>
        <div class="clear"></div>
      </hgroup>

      <%= render 'shared/application_body' %>

    </div>

    <div id="sidebar" class="span4">
      <div class="app-info">
        <h3>Info</h3>
        <h4><span class='icon'>Y</span> Get involved</h4>
        <p class='center'>
          <%= link_to 'Join the brigade to get involved!', join_brigade_url(@deployed_application.brigade, redirect_uri: deployed_application_path(@deployed_application)), class: 'btn btn-regular primary' if !can? :leave, @deployed_application.brigade%>
          <%= raw("You are a member of the brigade #{link_to @deployed_application.brigade.name, brigade_url(@deployed_application.brigade)} who is working on this applicaiton") if can? :leave, @deployed_application.brigade %>
        </p>

        <% if @deployed_application.brigade.point_of_contact_address.present? %>
          <h4><span class="icon">O</span> Connect</h4>
          <p><%= auto_link @deployed_application.brigade.point_of_contact_address %></p>
        <% end %>
        <h4><span class="icon">w</span> URL </h4>
        <% unless @deployed_application.deployed_url.nil? %>
          <p><%= link_to @deployed_application.deployed_url, @deployed_application.deployed_url %></p>
        <% end %>

        <h4><span class="icon">f</span> People <span id="user-name"></span></h4>
        <%= BrigadeDecorator.new(@deployed_application.brigade).decorated_members %>

        <h4><span class="icon">b</span> Share </h4>
        <p><a class='btn btn-mini' href="http://www.facebook.com/dialog/feed?app_id=<%= SOCIAL_NETWORKS['facebook_app_id']%>&redirect_uri=http://www.facebook.com&display=popup" id="fb-control">Share with facebook</a></p>
        <p>
          <a href="https://twitter.com/share" class="twitter-share-button" data-text='Check out this deployed application!' data-via="codeforamerica" data-size="small">Tweet</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </p>
        <%= render 'deployed_applications/social_network_modal' %>

        <h4><span class="icon">,</span> Deployed in</h4>
        <!-- minimap -->
        <div class='map', id='map' style="width: 265px; height: 230px;"></div>
        <div class='hidden' id='locations'>[<%= @deployed_application.location.to_json %>]</div>

      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyAU73pt7g1lj1KfSffmFgWfKHcbn_xJQyE&sensor=true"></script>
<script tpye='text/javascript'>
  var map;


  function initialize_map() {
    var myOptions = {
      center: new google.maps.LatLng(39.5, -98.35),
      zoom: 2,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById("map"), myOptions);
  }


  initialize_map();

  var locations = $.parseJSON($('#locations').text())

  $.each(locations, function(index, value){
    latlong = new google.maps.LatLng(value.latitude, value.longitude);
    marker = new google.maps.Marker({ position: latlong, title: value.name });
    marker.setMap(map)
  })

  map.setCenter( latlong );
</script>